### ISSUE TITLE
API for Configuration Updates

### ISSUE THREAD

**Issue by jhunt** [Proplex/depchecker#2]
Provide a pair of API calls for GET-ing and PUT-ing the configuration YAML.  Implement a version on the configuration, which gets incremented (time-based or monotonic) on every successful accept, to keep race conditions to a minimum.

**Comment by Proplex** [comment]
Implemented as of 232ee90db40a40f18385e2d3904df0760a06e330. Docs for the API can be found at [docs/API.md](docs/API.md). Subject to serious change down the road.
