### ISSUE TITLE
Support HTML/HTTP "index" listings

### ISSUE THREAD

**Issue by jhunt** [Proplex/depchecker#7]
As a diehard depchecker devotee, I would like to consume HTML-ified directory listings, looking for specific patterns, to extract version information from, like http://ftp.gnu.org/gnu/wget/

**Comment by Proplex** [comment]
Implemented as of 91ff9f52c3cd5f794837ca96fd34030aa5256241

Right now it only supports Apache and Nginx default-configuration HTTP index listings. I'm not sure if it's necessary to implement more support, but I think that's a good start.
